### ISSUE TITLE
Node.js version support

### ISSUE THREAD

**Issue by mike1808** [vov462/eslint-plugin-no-module-mutate#1]
Please figure out what Node.js version you can support. I noticed that you use `var` and `const`. If you want to support Node.js < 6 don't use `const`.

**Comment by vov462** [comment]
from the `package.json` of eslint
```json
"engines": {
    "node": "^6.14.0 || ^8.10.0 || >=9.10.0"
  }
```
i don't know if it is meaningful to bother with removing arrow functions, interpolation and const/let variables for older versions, given that eslint itself doesn't seem to bother. As of now `>=4.x.x` should work fine.

**Comment by mike1808** [comment]
if you make it an open source you should bother to make it work with the specified version

use `nvm` and try to use it with older node versions

However, your current code should work fine with v6

**Comment by vov462** [comment]
@mike1808 i tested it, it works fine on v4+, i've also updated the `engines` section in `package.json`. Thanks!
